[NOT FOR MERGE] Reproduce libdw opcode error
On kernels since 5.10, drgn gives me the following error when retrieving
values from some stack frames. This commit reliably reproduces the issue
on the vmtest kernels 5.10+. Below is a traceback.

Traceback (most recent call last):
  File "/home/stepbren/repos/drgn/tests/linux_kernel/test_stack_trace.py", line 122, in test_init_smoke
    bt.bt(self.prog.thread(1), show_vars=True)
  File "/home/stepbren/repos/drgn/drgn/helpers/linux/bt.py", line 191, in bt
    return _bt_internal(
  File "/home/stepbren/repos/drgn/drgn/helpers/linux/bt.py", line 130, in _bt_internal
    val = frame[local]
Exception: (null): .debug_loc+0x19e829: unknown DWARF expression opcode 0xf3

I'm not sure what the source of the error is. In my Oracle UEK based
repros, the libdw (elfutils) version used comes from the wheel, it's
version 188, which is >= the version used to build our kernels. So I
don't believe it's a simple versioning issue.